package ins.outweb.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-03-03T17:57:45.424+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.outweb.ins/", name = "SinosoftInter")
@XmlSeeAlso({ObjectFactory.class})
public interface SinosoftInter {

    @WebMethod
    @RequestWrapper(localName = "userDetail", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.UserDetail")
    @ResponseWrapper(localName = "userDetailResponse", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.UserDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ins.outweb.service.UserResp userDetail(
        @WebParam(name = "UserCode", targetNamespace = "")
        java.lang.String userCode
    );

    @WebMethod
    @RequestWrapper(localName = "outUname", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.OutUname")
    @ResponseWrapper(localName = "outUnameResponse", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.OutUnameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String outUname(
        @WebParam(name = "userCode", targetNamespace = "")
        java.lang.String userCode,
        @WebParam(name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    @WebMethod(operationName = "OnlineUser")
    @RequestWrapper(localName = "OnlineUser", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.OnlineUser")
    @ResponseWrapper(localName = "OnlineUserResponse", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.OnlineUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ins.outweb.service.ZsUserInfo onlineUser(
        @WebParam(name = "userCode", targetNamespace = "")
        java.lang.String userCode,
        @WebParam(name = "sessionId", targetNamespace = "")
        java.lang.String sessionId
    );

    @WebMethod
    @RequestWrapper(localName = "schoolList", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.SchoolList")
    @ResponseWrapper(localName = "schoolListResponse", targetNamespace = "http://service.outweb.ins/", className = "ins.outweb.service.SchoolListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ins.outweb.service.SchoolResp schoolList(
        @WebParam(name = "queryString", targetNamespace = "")
        java.lang.String queryString
    );
}
